Added option to switch camera view
One-Degree-North/mate-rnd-oqbot pull request #24
Opened 2021-06-21 08:00 UTC by fillnye

2021-06-21 08:20 UTC, lutet88 requested changes
some issues to fix.
consider renaming this to "updated camera view system" and also implement the third camera and its systems necessary here.

2021-06-21 08:20 UTC, lutet88 commented on controls_pyqt/gui.py
> +        if self.current_camera_layoutt == 0:
typo here

2021-06-21 08:20 UTC, lutet88 commented on controls_pyqt/gui.py
> +            self.current_camera_layout = 1
consider removing the `return` statements and place the constant setting of `self.current_camera_layout` with a `self.current_camera_layout += 1` and `self.current_camera_layout %= CAMERA_COUNT` or something similar

2021-06-21 08:20 UTC, lutet88 commented on controls_pyqt/gui.py
> +	if key_event.key() == Qt.Key_Slash
indentation problem here

2021-06-21 08:20 UTC, lutet88 commented on controls_pyqt/gui.py
> +	self.current_camera_layout = 0
indentation problem here.

2021-06-27 07:06 UTC, fillnye commented
Using a different codebase for this enhancement.

2021-06-27 07:06 UTC, closed without merging