Add MCU and MCU Interfacing
One-Degree-North/mate-rnd-oqbot pull request #4
Opened 2021-06-02 15:48 UTC by lutet88

This pull request adds

- Microcontroller-side code (mcu-code/mcu-code.ino)
- Microcontroller interfacing library (mcu-lib/mcu.py)
- a simple CLI for testing the microcontroller and its library (mcu-lib/mcu_cli.py)

2021-06-02 17:08 UTC, priime0 requested changes
In `mcu.py` consider defining all the bytes as constants for clarity, so we don't have to reference the packet structure too often.

2021-06-02 17:08 UTC, priime0 commented on .gitignore
> +
Random line here.

2021-06-02 17:08 UTC, priime0 commented on mcu-lib/mcu.py
> +NIL_BS = chr(0x00).encode('latin')
Consider renaming `NIL_BS` to something clearer or adding a comment.

2021-06-02 17:08 UTC, priime0 commented on mcu-lib/mcu.py
> +MAX_BS = chr(0xFF).encode('latin')
`MAX_BS` is not in use. What is it for? Consider renaming this as well.

2021-06-02 17:08 UTC, priime0 commented on mcu-lib/mcu.py
> +                pass
Consider printing an alert for the exception.

2021-06-02 17:08 UTC, priime0 commented on mcu-lib/mcu.py
> +        while next_byte != bs(0xAC) and self.__queue.qsize() >= 10:
What does `10` represent?

2021-06-02 17:08 UTC, priime0 commented on mcu-lib/mcu.py
> +        if self.__queue.qsize() < 9:
What does `9` represent? Use a variable.

2021-06-02 17:08 UTC, priime0 commented on mcu-lib/mcu.py
> +        if packet_data[8] != bs(0x74):
`0x74` should be a constant.

2021-06-02 17:08 UTC, priime0 commented on mcu-lib/mcu.py
> +        if packet_data[8] != bs(0x74):
Instead of `packet_data[8]`, maybe use `packet_data[-1]` as it's clearer that it's the last byte of a packet.

2021-06-02 17:08 UTC, priime0 commented on mcu-lib/mcu.py
> +        for i in range(9):  # 0x1 to 0x9
You can use the same variable as above for this `9`.

2021-06-02 17:08 UTC, priime0 commented on mcu-lib/mcu.py
> +        data_bs = packet.data[0] + packet.data[1] + packet.data[2] + packet.data[3]
From my understanding, these are bytes. Is your intent to add the bytes together or append them to the end of one another?

2021-06-02 17:08 UTC, priime0 commented on mcu-lib/mcu.py
> +        packet = bs(0xCA) + bs(cmd) + bs(param) + data + bs(0x47)
Use constants to define `0xCA` and `0x47`.

2021-06-02 17:08 UTC, priime0 commented on mcu-lib/mcu.py
> +        if packet.cmd == bs(0x00):
For each `if`/`elif` branch's `bs(byte)`, define a constant for the byte instead of using a comment.

2021-06-02 17:08 UTC, priime0 commented on mcu-lib/mcu.py
> +            print("invalid packet")
Maybe raise an exception?

2021-06-02 17:08 UTC, priime0 commented on mcu-lib/mcu.py
> +        data_bs = packet.data[0] + packet.data[1] + packet.data[2] + packet.data[3]
Unless they were converted to byte strings and I missed that.

2021-06-02 17:09 UTC, priime0 commented
You also appear to have included a binary file ` mcu-lib/__pycache__/packets.cpython-39.pyc`. Is this intentional?

2021-06-02 17:24 UTC, lutet88 commented on mcu-lib/mcu.py
> +                pass
One strange behavior of pyserial that I noticed from my own testing is that when reading packets at a high baud rate, there is a chance `SerialException` is raised, complaining about the read buffer. The handle here is to handle that behavior, and thus no action is required to handle this exception.

2021-06-02 17:26 UTC, lutet88 commented on mcu-lib/mcu.py
> +        data_bs = packet.data[0] + packet.data[1] + packet.data[2] + packet.data[3]
They are byte-strings. It's pretty annoying that I have to do this, unless I want to use a for loop, and that just adds unnecessary complexity.

2021-06-02 17:27 UTC, lutet88 commented
I will work on the changes in the morning.

2021-06-03 05:38 UTC, lutet88 commented on mcu-lib/mcu.py
> +            print("invalid packet")
We shouldn't raise an exception here, as we want the program to continue running when it receives an invalid packet, possibly due to a bit-flip on the command.

2021-06-03 05:44 UTC, priime0 approved these changes
Maybe @arora767287 should provide another perspective, but otherwise, this looks good to me :+1:.

2021-06-03 05:47 UTC, lutet88 commented
I don't expect any more significant changes to this pull request, so to speed up development, I'll merge it into main so @arora767287 can start work on comms.

2021-06-03 05:47 UTC, merged

2021-06-03 14:26 UTC, arora767287 commented
Wait on line 168, I'm probably not interpreting it the right way but if what is not packet?

2021-06-03 14:28 UTC, priime0 commented
> Wait on line 168, I'm probably not interpreting it the right way but if what is not packet?

End the function early.